# Generated by Django 5.0.7 on 2024-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='calificacion',
            new_name='examen_semestral',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota1',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
            preserve_default=False,
        ),
    ]
